version: '3.5'
services:
  topsify:
    build:
      context: .
      dockerfile: Dockerfile
    image: topsify
    container_name: topsify_app
    ports:
      - 3468:80
    restart: unless-stopped
    env_file:
      - .env